spring.application.name=order-service

server.port=8081

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.properties.spring.json.trusted.packages=*

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/order_notification_db
spring.datasource.username=root
spring.datasource.password=testing_password123

# JPA
spring.jpa.hibernate.ddl-auto=update

